# Generated by Django 3.2 on 2021-08-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_2fa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_2fa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ps_authkey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ps_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_points',
        ),
    ]
