# Generated by Django 3.2 on 2021-08-08 12:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(max_length=400)),
                ('return_url', models.CharField(max_length=400)),
                ('webhook_url', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'checkout',
            },
        ),
    ]
