# Generated by Django 3.2 on 2021-08-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='amount',
            field=models.FloatField(),
        ),
    ]
