# Generated by Django 3.2 on 2021-08-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='payment_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
