# Generated by Django 3.2 on 2021-08-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0002_payment_method_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCreds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_method.payment_method')),
            ],
            options={
                'db_table': 'payment_creds',
            },
        ),
    ]
