# Generated by Django 3.2 on 2021-08-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0003_paymentcreds'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcreds',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
